# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  postmark_api_token: 6c072a31-949b-4396-a225-a51af785541b
  secret_key_base: 90d563959b88c49c75decd23f7552f60b5009e7c7fa6b61c4f85b442ce93aa67ef3dcb2c68be6fe46b8185196d15c400883b097686bfd887cd93e31bf11a2040

test:
  postmark_api_token: 6c072a31-949b-4396-a225-a51af785541b
  secret_key_base: 441655a713fd896b6a60074daf1a92e73a12974a96a011d1157829ed99978bda9d3f87adc0ed60154b0a7b39604c0e490ff559b7985102a09e0fe63afad327d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  postmark_api_token: <%= ENV["POSTMARK_API_KEY"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
